language: python
python:
  - "2.7"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  - conda create --yes -n env_name python=$TRAVIS_PYTHON_VERSION pip numpy scipy matplotlib openpyxl=1.8.2 pandas nose flake8 pep8
  - source activate env_name
  - pip install coverage coveralls flake8
  - pip install -e '.[all]'
script:
  - flake8 platypus/*.py tests/*.py scripts/platypus setup.py
  - nosetests platypus --with-coverage --cover-package=platypus --cover-inclusive tests
after_success:
  - coveralls
